### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by gopherliu** [go-xiaohei/pugo-static#1] opened 2015-12-09 06:00 UTC
在welcome.md文件里写入内容如下：
![image](https://cloud.githubusercontent.com/assets/9070160/11677795/a3c0b5a2-9e7c-11e5-8641-1e3e0dc243c1.png)

网页显示内容如下：
![image](https://cloud.githubusercontent.com/assets/9070160/11677809/c8baf052-9e7c-11e5-8e7b-6cfe20ce413f.png)

**Comment by fuxiaohei** [comment] 2015-12-09 12:31
I can't reproduce the case with content :
This is the content啊啊啊啊啊啊啊啊啊啊啊啊啊～～～～～～～～～～

Can you send me the file in attachment ?

**Comment by fuxiaohei** [comment] 2015-12-13 13:19
I close the issue by no reply.

If it occurs again, reopen.

**Closed by fuxiaohei** 2015-12-13 13:19 UTC
